Develop
mkokoulin/secrets-manager pull request #1
Opened 2022-09-25 06:34 UTC by mkokoulin

2022-10-08 09:52 UTC, Bazys requested changes
есть вопросики

2022-10-08 09:52 UTC, Bazys commented on client/internal/loops/users.go
> +	secretHandler *handlers.SecretHandler
как `secretHandler` здесь используется?

2022-10-08 09:52 UTC, Bazys commented on client/internal/handlers/secrets.go
> +	userClient   *services.UserClient
как `userClient` здесь используется?

2022-10-08 09:52 UTC, Bazys commented on client/internal/handlers/users.go
> +func (uh *UserHandler) getUserCredentials(ctx context.Context) (string, string, error) {
а зачем здесь контекст?

2022-10-08 09:52 UTC, Bazys commented on server/internal/services/users.go
> +func (us *UsersService) RefreshToken(ctx context.Context, refreshToken string) (*auth.TokenDetails, error) {
а зачем здесь контекст?

2022-10-08 09:52 UTC, Bazys commented on server/internal/database/postgres.go
> +	err := pd.conn.Transaction(func(tx *gorm.DB) error {
```suggestion
	err := pd.conn.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
```

2022-10-08 09:52 UTC, Bazys commented on server/internal/handlers/grpc_secrets.go
> +			return ""
на 119 строке есть return, зачем тут?

2022-10-08 09:52 UTC, Bazys commented on server/internal/auth/jwt.go
> +	} else {
любишь ты лишние else

2022-10-08 09:52 UTC, Bazys commented on server/internal/models/secret.go
> +func (s *SecretData) Validate() error {
было rsd и вдруг стало s ?

2022-10-08 09:52 UTC, Bazys commented on client/internal/models/secrets.go
> +	var result []*pb.Data
```suggestion
	result := make([]*pb.Data, 0, len(s.Value))
```
если сразу известна длина массива, выделяй под него необходимый capacity, тогда append работает без переаллокаций памяти.

2022-10-08 09:52 UTC, Bazys commented on client/cmd/main.go
> +	envAddress := os.Getenv("ADDRESS")
опять инит?
я понимаю что в учебных примерах к кобре так написано, но можно посмотреть другие варианты?
например исходники того же github cli

2022-10-08 09:52 UTC, Bazys commented on server/internal/auth/jwt.go
> +		userID := claims["user_id"].(string)
```suggestion
		userID,ok := claims["user_id"].(string)
```
а вдруг не строка?

2022-10-08 09:52 UTC, Bazys commented on server/internal/auth/jwt.go
> +	mapClaims := token.Claims.(jwt.MapClaims)
```suggestion
	mapClaims, ok := token.Claims.(jwt.MapClaims)
```

2022-10-08 09:52 UTC, Bazys commented on server/cmd/main.go
> +	repo := database.NewPostgresDatabase(conn)
./main.go:70:47: cannot use repo (variable of type *database.PostgresDatabase) as type services.SecretsRepoInterface in argument to services.NewSecretsService:
	*database.PostgresDatabase does not implement services.SecretsRepoInterface (missing DeleteSecret method)
./main.go:71:41: cannot use secretsService (variable of type *services.SecretsService) as type handlers.SecretServiceInterface in argument to handlers.NewGRPCSecrets:
	*services.SecretsService does not implement handlers.SecretServiceInterface (missing DeleteSecret method)
	
при попытке скомпилировать

2022-10-08 09:52 UTC, Bazys commented on server/internal/auth/jwt.go
> +	log.Println("token has been generated")
а как же зеролог?

2022-10-10 16:37 UTC, mkokoulin commented on client/internal/loops/users.go
> +	secretHandler *handlers.SecretHandler
done

2022-10-10 16:37 UTC, mkokoulin commented on client/internal/handlers/secrets.go
> +	userClient   *services.UserClient
done

2022-10-10 16:38 UTC, mkokoulin commented on client/internal/handlers/users.go
> +func (uh *UserHandler) getUserCredentials(ctx context.Context) (string, string, error) {
done

2022-10-10 16:38 UTC, mkokoulin commented on server/internal/services/users.go
> +func (us *UsersService) RefreshToken(ctx context.Context, refreshToken string) (*auth.TokenDetails, error) {
done

2022-10-10 16:38 UTC, mkokoulin commented on server/internal/database/postgres.go
> +	err := pd.conn.Transaction(func(tx *gorm.DB) error {
done

2022-10-10 16:38 UTC, mkokoulin commented on client/cmd/main.go
> +	envAddress := os.Getenv("ADDRESS")
done

2022-10-10 16:39 UTC, mkokoulin commented on server/internal/auth/jwt.go
> +		userID := claims["user_id"].(string)
Тут всегда строка

2022-10-10 16:40 UTC, mkokoulin commented on server/internal/auth/jwt.go
> +	log.Println("token has been generated")
done

2022-10-10 16:42 UTC, mkokoulin commented on server/cmd/main.go
> +	repo := database.NewPostgresDatabase(conn)
done

2022-10-17 21:12 UTC, Bazys approved these changes
есть конечно к чему придраться, но в целом работа выглядит законченной

2022-10-18 05:33 UTC, merged